config/routes.rb
BookCatalogue::Application.routes.draw do

  resources :authors, :subjects, :class_records, :audits

  resources :grades do
    get 'statistics', :on => :member
  end

  resources :books do
    get 'statistics', :on => :member
    get 'title_data', :on => :collection
    get 'popular', :on => :collection
  end

  resources :checkout_items do
    post 'checkin_many', :on => :collection
    post 'batch_checkin', :on => :collection
    post 'batch_checkout', :on => :collection
  end
  
  resources :user_sessions, :only => [ :new, :create, :destroy ]

  match '/batch-checkout', :to => 'pages#batch_checkout', :as => 'batch_checkout'
  match '/batch-checkin', :to => 'pages#batch_checkin', :as => 'batch_checkin'
  match '/search_bar', :to => 'books#search_bar'
  match '/csv', :to => 'books#csv'

  match '/checkout_items/checkin', :to => 'checkout_items#checkin', :as => 'checkin'

  root :to => "pages#home", :as => "home"
  
  match 'admin' => 'pages#admin', :as => "admin"
  match 'stats' => 'pages#stats', :as => "stats"
  match 'class_stats' => 'pages#class_stats', :as => "class_stats"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/grade.rb
# coding: utf-8
class Grade < ActiveRecord::Base
  has_many :class_records

  validates_presence_of :year

  default_scope :order => 'year'


  def pretty_year
    if year == 0
      "Jardin"
    elsif year == 1
      "1ère année"
    else
      "#{year}ème année"
    end
  end


  # Some statistic functions...

  def teacher_present_count
    class_records.where(:teacher => true).count
  end

  def teacher_absent_count
    class_records.where(:teacher => false).count
  end

  def teacher_attendance
    present = teacher_present_count
    absent = teacher_absent_count
    if present + absent == 0
      "N/A"
    else
      "#{(present * 100.0 / (present + absent)).round} %"
    end
  end

  def average_attendance
    students = ClassRecord.where(:grade_id => id).average('attendance')
    students.nil? ? 0 : students.round(1)
  end

  def stats
    return [[]] if class_records.empty?
    data = {}
    class_records.reverse.each_with_index do |r, i|
      data[i] = r.attendance || 0
    end
    return data.to_a
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  def new
    @grade = Grade.new
  end
  
  def create
    @grade = Grade.new(params[:grade])
    if @grade.save
      redirect_to @grade
    else
      render 'new'
    end
  end

  def show
    @grade = Grade.find(params[:id])
  end

  def edit
    @grade = Grade.find(params[:id])
  end

  def update
    @grade = Grade.find(params[:id])
    @grade.update_attributes(params[:grade])
    if @grade.save
      redirect_to @grade
    else
      render 'edit'
    end
  end

  def index
    @grades = Grade.all
  end


 def statistics
    @grade = Grade.find(params[:id])
    @filename = "gr-#{@grade.year}-statistics.csv"
    @output_encoding = 'UTF-8'

    respond_to do |format|
      format.js { render :json => @grade.stats.to_json }
      format.csv 
    end
  end

end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<div class="span12">
  <%= form_for(@grade) do |f| %>
    <% if @grade.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</p>

        <ul>
          <% @grade.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <fieldset>
      <div class="clearfix">
        <%= f.label :year, "Grade Year" %>
        <div class="input">
          <%= f.text_field :year, {:class => "xlarge" } %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :name, "Grade Name" %>
        <div class="input">
          <%= f.text_field :name, {:class => "xlarge" } %>
        </div>
      </div>



      <div class="clearfix">
        <%= f.label :number_students, "Number of Students" %>
        <div class="input">
          <%= f.text_field :number_students, {:class => "xlarge" } %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :notes, "Notes" %>
        <div class="input">
          <%= f.text_area :notes, {:class => "xlarge" } %>
        </div>
      </div>


      <div class="actions">
        <%= f.submit :class => "btn primary"  %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/grades/_grade.html.erb
<li><%= link_to grade.name, grade %>, Number of students: <%= grade.number_students %></li>

app/views/grades/edit.html.erb
<h1>Edit grade <%= @grade.year %></h1>
<%= render 'form' %>

app/views/grades/index.html.erb
<p><%= link_to "← Retourner à les tâches administratives", admin_path %></p>
<h1>Selectionnez une classe</h1>
<ul>
<%= render @grades %>
<li><%= link_to "Voir toutes les visites récentes", class_records_path %></li>
</ul>
<p>-------------------</p>
<p><%= link_to "Ajouter une nouvelle classe", new_grade_path %> </p> 

app/views/grades/new.html.erb
<h1>Add a new class:</h1>
<p>Make sure you haven't added them already!</p>
<%= render 'form' %>

app/views/grades/show.html.erb
<%= javascript_include_tag 'class_stats' %>
<p><%= link_to "← Retourner à la liste des classes", grades_path %></p>
<p><%= link_to "← Retourner à les taches adminastratives", admin_path %></p>
<h1>Classe: <%= @grade.name %></h1>
<ul>
  <li>Effectif: <%= @grade.number_students %></li>
  <li>Assistance moyen par visite: <%= @grade.average_attendance %> élèves par visite</li>
  <li>Assistance du maître: <%= @grade.teacher_attendance %></li>
</ul>
<p style="text-align: right; padding-right: 100px;">(<%= link_to "Modifier la classe", edit_grade_path(@grade) %> | 
<%= link_to "Télécharger les statistiques", statistics_grade_path(@grade) + ".csv" %>)</p>
<h3>Notes Générales:</h3>
<p><%= @grade.notes %></p>
<ul class="tabs" data-tabs="tabs" style="margin-top: 30px">
  <li class="active"><a href="#notes">Notes</a></li>
  <li><a href="#summary">Summary</a></li>
</ul>
<div id="tab-content" class="tab-content" >
  <div id="summary">
    <p><strong>Cliquez sur la date pour voir les notes de cette visite:</strong></p>
    <table class="zebra-striped sorted" data-sort-column="0" data-sort-order="0">
      <thead><th>Date</th><th>Temps passé dans la bibliothèque</th><th>Assistance</th><th>Maître présent?</th></thead>
      <tbody>
        <% @grade.class_records.each do |class_record| %>
          <tr>
            <td><%= link_to "#{class_record.arrival.strftime("%Y-%m-%d")}", class_record %></td>
            <td><%= class_record.delta %> h</td>
            <td><%= class_record.attendance %></td>
            <td <%= "style='background-color:red;'" unless class_record.teacher %>><%= class_record.teacher %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h2>Statistiques d'assistance:</h2>
    <div id="graph-container" data-grade-id="<%= @grade.id %>" style="width:400px; height:300px; margin:25px;"></div>
  </div>

  <div id="notes" class="active">
    <p><strong>Cliquez sur la date pour voir les detailles de cette visite:</strong></p>
    <table class="zebra-striped sorted" data-sort-column="0" data-sort-order="1" >
      <thead><th>Date</th><th>Notes</th></thead>
      <tbody>
        <% @grade.class_records.each do |class_record| %>
          <tr>
            <td><%= link_to "#{class_record.arrival.strftime("%Y-%m-%d")}", class_record %></td>
            <td><%= class_record.notes %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>