config/routes.rb
BookCatalogue::Application.routes.draw do

  resources :authors, :subjects, :class_records, :audits

  resources :grades do
    get 'statistics', :on => :member
  end

  resources :books do
    get 'statistics', :on => :member
    get 'title_data', :on => :collection
    get 'popular', :on => :collection
  end

  resources :checkout_items do
    post 'checkin_many', :on => :collection
    post 'batch_checkin', :on => :collection
    post 'batch_checkout', :on => :collection
  end
  
  resources :user_sessions, :only => [ :new, :create, :destroy ]

  match '/batch-checkout', :to => 'pages#batch_checkout', :as => 'batch_checkout'
  match '/batch-checkin', :to => 'pages#batch_checkin', :as => 'batch_checkin'
  match '/search_bar', :to => 'books#search_bar'
  match '/csv', :to => 'books#csv'

  match '/checkout_items/checkin', :to => 'checkout_items#checkin', :as => 'checkin'

  root :to => "pages#home", :as => "home"
  
  match 'admin' => 'pages#admin', :as => "admin"
  match 'stats' => 'pages#stats', :as => "stats"
  match 'class_stats' => 'pages#class_stats', :as => "class_stats"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/class_record.rb
class ClassRecord < ActiveRecord::Base
  belongs_to :grade

  validates_presence_of :grade
  validates_format_of :attendance, :with => /\d+/, :message => "Il faut utiliser un nombre"
  default_scope :order => 'arrival DESC'


  def date
    (arrival || Time.now.utc).strftime("%d/%m/%Y")
  end

  def time_in
    arrival || Time.now.utc - (Time.now.utc.min).minutes
  end


  def time_out
    departure || time_in + 1.hour
  end

  def delta
    ((departure - arrival)/3600).round(1)
  end

  def teacher_attendance
    teacher ? 1 : 0
  end

  def teacher_attendance=(value)
    if value.to_i == 1
      self.teacher = true
    else
      self.teacher = false
    end
  end

  def date_son
    if arrival.nil?
      {:year => Time.now.utc.year, :month => Time.now.utc.month, :day => Time.now.utc.day }.to_json
    else
      {:year => arrival.year, :month => arrival.month, :day => arrival.day }.to_json
    end
  end

  # fixes parameters hash from form, to use arrival and departure with full datetime
  def self.fix_params(params)

    date = JSON.parse(params[:class_record][:date_son])
    
    hour_in = params[:class_record]["time_in(4i)"].to_i
    minute_in = params[:class_record]["time_in(5i)"].to_i
    
    hour_out = params[:class_record]["time_out(4i)"].to_i
    minute_out = params[:class_record]["time_out(5i)"].to_i
    
    params[:class_record].merge!(
      :arrival => Time.utc(date["year"], date["month"], date["day"], hour_in, minute_in),
      :departure => Time.utc(date["year"], date["month"], date["day"], hour_out, minute_out)
    )
    return params
  end

end

app/controllers/class_records_controller.rb
class ClassRecordsController < ApplicationController


  def new
    @class_record = ClassRecord.new
  end

  def create
    grade = Grade.find(params[:class_record][:grade_id])
    data = ClassRecord.fix_params(params)

    @class_record = grade.class_records.build(:arrival => data[:class_record][:arrival],
                      :departure => data[:class_record][:departure],
                      :teacher_attendance => data[:class_record][:teacher_attendance],
                      :attendance => data[:class_record][:attendance],
                      :notes => data[:class_record][:notes])

    if @class_record.save
      redirect_to grade #@class_record
    else
      render 'new'
    end
  end

  def edit
    @class_record = ClassRecord.find(params[:id])
  end

  def update
    @class_record = ClassRecord.find(params[:id])
    data = ClassRecord.fix_params(params)

    @class_record.update_attributes(:arrival => data[:class_record][:arrival],
                      :departure => data[:class_record][:departure],
                      :teacher_attendance => data[:class_record][:teacher_attendance],
                      :attendance => data[:class_record][:attendance],
                      :notes => data[:class_record][:notes])
    if @class_record.save
      redirect_to @class_record
    else
      render 'edit'
    end
  end

  def show
    @class_record = ClassRecord.find(params[:id])
  end

  def index
    @class_records = ClassRecord.all
  end
end

app/helpers/class_records_helper.rb
module ClassRecordsHelper
end

app/views/class_records/_class_record.html.erb
<tr>
  <td><%= link_to "#{class_record.arrival.strftime("%Y/%m/%d")}", class_record %></td>
  <td><%= class_record.grade.name %></td>
  <td><%= class_record.delta %> h</td>
  <td><%= class_record.attendance %></td>
  <td <%= "style='background-color:red;'" unless class_record.teacher %>><%= class_record.teacher %></td>
</tr>

app/views/class_records/_form.html.erb
<div class="span12">
  <%= form_for(@class_record) do |f| %>
    <% if @class_record.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(@class_record.errors.count, "error") %> prohibited this class_record from being saved:</p>

        <ul>
          <% @class_record.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <fieldset>

      <div class="clearfix">
        <%= f.label :date, "Date", {:style => "padding-right: 20px;" } %>
        <%= f.text_field :date, { :id => "datepicker" } %>

        <%= f.hidden_field :date_son, {:id => "date_object" } %>

      </div>
      <div class="clearfix">
        <%= f.label :time_in, "Heure d'arrivée", {:style => "padding-right: 20px;" } %>
        <%= f.time_select :time_in, {:ignore_date => true, :minute_step => 15}, {:class => "mini"} %>
      </div>

      <div class="clearfix">
        <%= f.label :time_out, "Heure de sortie" , {:style => "padding-right: 20px;" }%>
        <%= f.time_select :time_out, {:ignore_date => true, :minute_step => 15}, { :class => "mini"}  %>
      </div>


      <div class="clearfix">
        <%= f.label :grade_id, "Classe", {:style => "padding-right: 20px;" } %>
        <%= f.select :grade_id, Grade.all.collect{ |g| [g.name, g.id]}, { :class => "span2"}  %>
      </div>
      <div class="clearfix">
        <%= f.label :attendance, "Effectif", {:style => "padding-right: 20px;" } %>
        <%= f.text_field :attendance %>

      </div>

      <div class="clearfix">
        <%= f.label :teacher_attendance, "Le Maître était présent?", {:style => "padding-right: 20px;" } %>
        <%= f.check_box :teacher_attendance %>
      </div>


      <div class="clearfix">
        <%= f.label :notes, "Notes" %>
        <div class="input">
          <%= f.text_area :notes, {:class => "xlarge" } %>
        </div>
      </div>


      <div class="actions">
        <%= f.submit :class => "btn primary"  %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/class_records/edit.html.erb
<h1>Edit <%= "#{@class_record.grade.pretty_year}, #{@class_record.date}" %></h1>
<%= render 'form' %>

app/views/class_records/index.html.erb
<p><%= link_to "← Retourner à la liste", grades_path %></p>
<h1>Toutes les visites</h1>
<p>Cliquez sur la date pour voir les notes de cette visite.</p>
<table class="zebra-striped sorted" data-sort-column="0" data-sort-order="1">
  <thead><th>Date</th><th>Classe</th><th>Temps passé dans la bibliothéque</th><th>Assistance</th><th>Maître présent??</th></thead>
  <tbody>
    <%= render @class_records %>
  </tbody>
</table>

app/views/class_records/new.html.erb
<h1>Enregistrer une classe!</h1>
<%= render 'form' %>

app/views/class_records/show.html.erb
<p><%= link_to "← Retourner à la liste de #{@class_record.grade.name}", grade_path(@class_record.grade) %></p>
<h1>Class Record: <%= @class_record.grade.name %></h1>
<ul>
  <li>Date: <%= @class_record.arrival.strftime("%d/%m/%Y") %></li>
  <li>Heure d'arrivée: <%= @class_record.arrival.to_s(:time) %></li>
  <li>Heure de sortie: <%= @class_record.departure.to_s(:time) %></li>
  <li>Assistance: <%= @class_record.attendance %> élèves</li>
  <li>Le maître <%= @class_record.teacher ?  "étais" : "n'étais pas" %> présent.</li>
</ul>
<h3>Notes on classtime:</h3>
<p><%= @class_record.notes %></p>
<%= link_to "edit", edit_class_record_path(@class_record) %>