config/routes.rb
BookCatalogue::Application.routes.draw do

  resources :authors, :subjects, :class_records, :audits

  resources :grades do
    get 'statistics', :on => :member
  end

  resources :books do
    get 'statistics', :on => :member
    get 'title_data', :on => :collection
    get 'popular', :on => :collection
  end

  resources :checkout_items do
    post 'checkin_many', :on => :collection
    post 'batch_checkin', :on => :collection
    post 'batch_checkout', :on => :collection
  end
  
  resources :user_sessions, :only => [ :new, :create, :destroy ]

  match '/batch-checkout', :to => 'pages#batch_checkout', :as => 'batch_checkout'
  match '/batch-checkin', :to => 'pages#batch_checkin', :as => 'batch_checkin'
  match '/search_bar', :to => 'books#search_bar'
  match '/csv', :to => 'books#csv'

  match '/checkout_items/checkin', :to => 'checkout_items#checkin', :as => 'checkin'

  root :to => "pages#home", :as => "home"
  
  match 'admin' => 'pages#admin', :as => "admin"
  match 'stats' => 'pages#stats', :as => "stats"
  match 'class_stats' => 'pages#class_stats', :as => "class_stats"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/pages/admin.html.erb
<%= javascript_include_tag 'admin' %>
<h1>Tâches administratives</h1>
<p><b>Gérer la collection:</b></p>
<ul>
  <li><%= link_to "Liste des livres", books_path %></li>
  <li><%= link_to "Telecharger la liste des livres", "/books.csv" %></li>
  <li><%= link_to "Ajouter un livre", new_book_path %></li>
  <li><%= link_to "Contrôler la collection", new_audit_path %></li>
  <li><%= link_to "Voir les audits passés", audits_path %></li>
</ul>
<p><b>Examiner quel'que statistiques sur la collection:</b></p>
<ul>
  <li><a href="#" data-controls-modal="parent-books-currently-out">Liste de livre retirés</a></li>
  <li><%= link_to "Statistiques general", stats_path %></li>
</ul>
<p>(Pour examiner les statistiques d'un livre particulier, il faut chercher ce livre et cliquer sur "Statistique" en bas de la page.)</p>

<p><b>Retiré/Rendu avec vitesse!</b></p>
<ul>
  <li><%= link_to "Rendre beaucoup de livres", batch_checkin_path %></li>
  <li><%= link_to "Retrirer beaucoup de livres", batch_checkout_path %></li>
</ul>
<div id="parent-books-currently-out" class="modal hide fade">
  <%= render :partial => 'checkout_items/currently_out' %>
</div>

<p><b>Enregistrer les classes qui utilisent la bibliothèque</b></p>
<ul>
  <li><%= link_to "Enregistrer une nouvelle visite", new_class_record_path %></li>
  <li><%= link_to "Voir les notes des visites précedentes", grades_path %></li>
</ul>

app/views/pages/batch_checkin.html.erb
<%= javascript_include_tag "batch-checkin" %>
<div id="batch-checkin-form">
  <% if @checkout_items.empty? %>
    Il n'y a pas des livres rendus.
  <% else %>
    <%= form_for "checkout_item[]", :as => :checkout_item, :url => batch_checkin_checkout_items_path, :html => { :method => :post, :id => "batch-checkin-form", :class => "span12" }  do |f| %>
      <fieldset>
        <table class="zebra-striped sorted">
          <thead><th>Inscrire</th><th>Titre</th><th>Notes</th><th>Retrir un autre</th></thead>
          <tbody>
            <% for @checkout_item in @checkout_items %>
              <tr>
                <td><%= f.check_box :status, {:checked => false} %></td>
                <td><%= @checkout_item.book.title %></td>
                <td><%= @checkout_item.notes %></td>
                <td><%= text_field_tag "checkout_item[#{@checkout_item.id}][next]", nil, :class => "autocomplete_book_title span3" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="actions">
          <%= f.submit("Inscrire", { :class => "btn primary" }) %>
        </div>
      </fieldset>
    <% end %>
  <% end %>
</div>
<hr />
<div>
  <%= link_to "Retrirer plusieur livres", batch_checkout_path %>
</div>

app/views/pages/batch_checkout.html.erb
<%= javascript_include_tag 'batch-checkout' %>
<div>

  <%= form_for CheckoutItem.new, :url => batch_checkout_checkout_items_path, :html => { :method => :post, :id => "batch-checkout-form" } do |f| %> 

    <table class="zebra-striped" id="batch-checkout-table">
      <thead><th>Livre</th><th>Notes</th></thead>
        <tbody id="checkout-table-body">
          <tr>
            <td><%= text_field "book_title", "1", {:class => "xlarge autocomplete_title" , "data-index" => "1"} %></td>
            <td><%= text_field "checkout_notes", "1",  {:class => "xlarge", "data-index" => "1" } %></td>
          </tr>
        </tbody>
      </table>

    <% end %>
    <div class="actions">
      <input id="submit-batch-checkout" type="submit" value="Retirer toutes" class="btn primary">
    </div>
</div>

<div>
  <%= link_to "Rendre les livres", batch_checkin_path %>
</div>

app/views/pages/class_stats.html.erb
<h1>Class Usage statistics</h1>
<table class="zebra-striped sorted" data-sort-column="0">
  <thead><th>Class</th><th>Number of times come</th><th>Teacher attendance</th><th>average attendance</th></thead>
  <tbody>
    <% @grades.each do |g| %>
      <tr>
        <td><%= g.name %></td>
        <td><%= g.class_records.count %></td>
        <td><%= g.teacher_present_count %> present;  <%= g.teacher_absent_count %> absent = <%= g.teacher_attendance %></td>
        <td><%= g.average_attendance %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<p><%= link_to "Download", class_stats_path + ".csv" %></p>

app/views/pages/home.html.erb
<%= javascript_include_tag 'search-bar' %>
<div class="spacer"></div>
<div class="span10">
  <h1 class="center-text">Cherchez un livre!</h1>
  <form action="/" method="get">
    <input id="search" name="search" class="span10" value="<%= @search_query %>"/>
    <div class="search-button-area">
      <input id="search-button"  type="submit" value="chercher" class="btn primary">
    </div>
  </form>

  <% if ! @books.nil? %>
    <table class="zebra-striped sorted">
      <thead><th>Collection</th><th>Titre</th><th>Sujet</th></thead>
        <tbody>
          <% if @books.empty? %>
            <tr><td></td><td>Pas de resultats.</td><td></td></tr>
          <% else %>
            <%= render @books, :locals => { :search_query => @search_query } %>
          <% end %>

        </tbody>
      </table>
    <% end %>
  </div>

app/views/pages/stats.html.erb
<h1>Statistiques General</h1>
  <table class="zebra-striped">
      <tbody>
            <tr><td>Nombre de livres (en totale):</td><td><%= @book_count %></td></tr>
            <tr><td>Nombre de livres de la collection NEP:</td><td><%= @NEP_count %></td></tr>
            <tr><td>Nombre de livres de la collection Diarra:</td><td><%= @Diarra_count %></td></tr>
            <tr><td>Nombre totale de livres retirés:</td><td><%= @checkout_count %></td></tr>
            <tr><td>Livres populaires: <br />
                <%= link_to "(Telecharger les statistiques)", "/books/popular.csv" %>
                </td><td>
                <ol>
                  <% @popular.each do |b| %>
                    <li><%= link_to b.title, book_path(b) %></li>
                  <% end %>
                </ol>
              </td></tr>
      </tbody>
    </table>