config/routes.rb
BookCatalogue::Application.routes.draw do

  resources :authors, :subjects, :class_records, :audits

  resources :grades do
    get 'statistics', :on => :member
  end

  resources :books do
    get 'statistics', :on => :member
    get 'title_data', :on => :collection
    get 'popular', :on => :collection
  end

  resources :checkout_items do
    post 'checkin_many', :on => :collection
    post 'batch_checkin', :on => :collection
    post 'batch_checkout', :on => :collection
  end
  
  resources :user_sessions, :only => [ :new, :create, :destroy ]

  match '/batch-checkout', :to => 'pages#batch_checkout', :as => 'batch_checkout'
  match '/batch-checkin', :to => 'pages#batch_checkin', :as => 'batch_checkin'
  match '/search_bar', :to => 'books#search_bar'
  match '/csv', :to => 'books#csv'

  match '/checkout_items/checkin', :to => 'checkout_items#checkin', :as => 'checkin'

  root :to => "pages#home", :as => "home"
  
  match 'admin' => 'pages#admin', :as => "admin"
  match 'stats' => 'pages#stats', :as => "stats"
  match 'class_stats' => 'pages#class_stats', :as => "class_stats"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/book.rb
class Book < ActiveRecord::Base
  require 'date'
  require 'date/delta'

  after_initialize :init


  has_many :checkout_items, :dependent => :destroy, :dependent => :destroy

  has_many :writings
  has_many :authors, :through => :writings

  has_many :subject_tags
  has_many :subjects, :through => :subject_tags

  has_and_belongs_to_many :audits

  scope :subject, lambda {|subject| Book.joins(:subjects).where(:subjects => {:name => subject} ) }
  scope :subject_search, lambda {|subject| Book.joins(:subjects).where('subjects.name LIKE ?', "%#{subject}%" ) }

  
  def num_copies
    nep = self.num_copies_nep.nil? ? 0 : self.num_copies_nep    # gotta be a better way...
    emd = self.num_copies_emd.nil? ? 0 : self.num_copies_emd
    nep + emd
  end

  def collection
    if self.num_copies_nep == 0
      coll = "Diarra"
    elsif self.num_copies_emd == 0
      coll = "NEP"
    else
      coll = "NEP / Diarra"
    end
    return coll
  end

  def generate(params)
    data = params['book']
    data['num_copies_nep'] = 0 if data['num_copies_nep'].blank?
    data['num_copies_emd'] = 0 if data['num_copies_emd'].blank?

    self.attributes=(data)
    self.subject_fields=(params['subjects'])
    self.author_fields=(params['authors'])
  end

  def author_fields=(authors_hash)
    author_arry = []
    authors_hash.values.each do |a|
      next if a['first'] == "" and a['last'] == ""
      author_arry << Author.find_or_create_by_first_and_last(a) 
    end
    self.authors = author_arry
  end

  def subject_fields=(subjects_hash)
    subject_arry = []
    subjects_hash.values.each do |s|
      next if s['name'] == ""
      subject_arry << Subject.find_or_create_by_name(s)
    end
    self.subjects = subject_arry
  end

  def checked_out
    self.checkout_items.out.length
  end

  def checked_in
    self.num_copies - self.checkout_items.out.length
  end

  def csv_array
    authors_str = self.authors.map{|a| "#{a.last},#{a.first}"}.join(";")
    subjects_str = self.subjects.map{|s| "#{s.name}"}.join(";")
    authors_str = "" if authors_str.empty?
    subjects_str = "" if subjects_str.empty?

    [self.id.to_s, self.title.to_s, self.pub_year.to_s, self.genre.to_s, self.age_group.to_s, self.num_pages.to_s, self.num_copies_nep.to_s, self.num_copies_emd.to_s, self.series_title.to_s, self.series_number.to_s, self.language, self.summary.to_s, self.notes.to_s, authors_str, subjects_str, self.checkout_items.count]

  end

  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ? OR summary LIKE ?', "%#{search}%", "%#{search}%"])
    end
  end

  def self.popular(limit)
    Book.limit(limit).order('checkout_count DESC')
  end

  def stats
    checkouts = self.checkout_items
    return [[]] if checkouts.empty?

    offset = delta(Time.now, checkouts[0].created_at)

    data = {} 
    (0..offset).each do |i|
      data[i - offset] = self.checkout_tally(Time.now - i.days)
    end
    
    return data.to_a
      
  end

  def checkout_tally(day)
    self.checkout_items.count_date(day).length
  end

  private
  def delta(d1, d2)
    Date::Delta.diff(d1.to_date, d2.to_date).days
  end

  def init
    self.num_copies_nep ||= 1
  end
end

app/controllers/books_controller.rb
# coding: utf-8
class BooksController < ApplicationController

  before_filter :authenticate, :only => [:new, :create, :edit, :update, :destroy]

  
  def new
    @book = Book.new
    @subject_list = [Subject.new]
    @author_list = [Author.new]
  end

  def create

    @book = Book.new
    @book.generate(params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @subject_list = @book.subjects
    @author_list = @book.authors
    @author_list = [Author.new] if @author_list.empty?
    @subject_list = [Subject.new] if @subject_list.empty?
  end

  def update

    @book = Book.find(params[:id])
    @book.generate(params)

    if @book.save
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Le livre a été supprimé!"
    redirect_to books_path
  end

  def show

    begin
      ref_url = request.referrer
      @from_search = ref_url.split("/")[3][0..7] == "?search=" 
    rescue
      @from_search = false
    end
    

    @checkout = CheckoutItem.new
    @book = Book.find(params[:id])
    @checkout_items = @book.checkout_items.out
    @checkout_item = CheckoutItem.new
  end

  def index
    @books = Book.includes(:subjects).order('title ASC')
    @filename = 'toutes-livres.csv'
    @output_encoding = 'UTF-8'

    respond_to do |format|
      format.html
      format.csv 
    end
  end
      

  def search_bar
    output = Book.order("title ASC").map { |bt| bt.title }
    output.concat(Subject.order("name ASC").map { |st| st.name })
    #output = Book.search('pages').map{|bt| bt.title }

    
    render :json => output.to_json
  end

  def title_data
    output = Book.order("title ASC").map { |bt| bt.title }
    render :json => output.to_json
  end


  def statistics
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html
      format.js { render :json => @book.stats.to_json }
      format.csv
    end
  end

  def popular
    @books = Book.order('checkout_count DESC')
    @filename = 'livres-populaires.csv'
    @output_encoding = 'UTF-8'
    respond_to do |format|
      format.csv
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>
  <td><%= book.collection %></td>
  <td width="50%"><%= link_to book.title, book_path(book) %> 
    <% if current_user %>
      <!--      | <span class="label warning"><%= link_to "Edit", edit_book_path(book.id) %></span> -->
    <% end %>
    </td>
  <td><% book.subjects.each do |s| %><%= "#{s.name}" %><%= ", " unless s == book.subjects.last %><% end %></td>
</tr>

app/views/books/_checkout_history.html.erb
<div id="checkout-history" >
  <div class="modal-header">
    <h3></h3>
  </div>
  <div class="modal-body">
  <ul>
    <% @book.checkout_items.out.each do |ci| %>
      <li><%= ci.notes %></li>
    <% end %>
    <%= "Personne." if @book.checkout_items.out.empty? %>
  </ul>
</div>

<div class="modal-footer">
  <a href="#" id="close-current-checkouts" class="btn primary">OK</a>
</div>
</div>

app/views/books/_checkout_items.html.erb
<div id="current-checkouts" >
  <div class="modal-header">
    <h3>Qui a cet livre?</h3>
  </div>
  <div class="modal-body">
    <ul>
      <% @book.checkout_items.out.each do |ci| %>
        <li><%= ci.notes %></li>
      <% end %>
      <%= "Personne." if @book.checkout_items.out.empty? %>
    </ul>
  </div>

  <div class="modal-footer">
    <a href="#" id="close-current-checkouts" class="btn primary">OK</a>
  </div>
</div>

app/views/books/_form.html.erb
<%= javascript_include_tag 'book-form' %>

<div class="span12">
  <%= form_for(@book) do |f| %>
    <fieldset>

      <div class="clearfix">
        <%= f.label :title, "Titre" %>
        <div class="input">
          <%= f.text_field :title,  {:class => "xlarge" } %>
        </div>
      </div>

      <div class="multi-inputs">
        <div id="author-inputs"  data-counter="0">
          <% @author_list.each_index do |i| %>
            <div class="row">
              <div class="span10 offset1">
                <div class="clearfix">
                  <%= label "authors[#{i}]", :last, "Auteur (Nom)" %>
                  <div class="input">
                    <%= text_field "authors[#{i}]", :last, {:class => "xlarge", :value => @author_list[i].last } %>
                  </div>
                </div>
                <div class="clearfix">
                  <%= label "authors[#{i}]", :first, "Auteur (Prenom)" %>
                  <div class="input">
                    <%= text_field "authors[#{i}]", :first, {:class => "xlarge", :value => @author_list[i].first } %>
                  </div>
                </div>
              </div>
            </div>
          <% end %> 
        </div>

        <div class="clearfix input">
          <a href="#" id="new-author">Ajouter autre auteur</a>
        </div>
      </div> <!-- end .multi-inputs -->
      <div class="clearfix">
        <%= f.label :pub_year, "Date de publication" %>
        <div class="input">
          <%= f.text_field :pub_year,  {:class => "xlarge" } %>
        </div>
      </div>


      <div class="clearfix">
        <%= f.label :genre %>
        <div class="input">
          <%= f.text_field :genre,  {:class => "xlarge" } %>
        </div>
      </div>

      <div class="multi-inputs">
        <div id="subject-inputs" data-counter="0">
          <% @subject_list.each_index do |i| %>
            <div class="clearfix">
              <%= label "subjects[#{i}]", :name, "Sujet" %>
              <div class="input">
                <%= text_field "subjects[#{i}]", :name, {:class => "xlarge subject", :value =>  @subject_list[i].name} %>
              </div>
            </div>
          <% end %>
        </div> <!-- end #subject-inputs -->

        <div class="clearfix input">
          <a href="#" id="new-subject">Ajouter autre sujet</a>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :age_group, "Tranche d'âge" %>
        <div class="input">
          <%= f.text_field :age_group,  {:class => "xlarge" } %>
        </div>
      </div>


      <div class="clearfix">
        <%= f.label :num_pages, "Nombre de pages" %>
        <div class="input">
          <%= f.text_field :num_pages,  {:class => "xlarge" } %>
        </div>
      </div>


      <div class="clearfix">
        <%= f.label :num_copies_nep, "Nombre de copies NEP" %>
        <div class="input">
          <%= f.text_field :num_copies_nep,  {:class => "xlarge" } %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :num_copies_emd, "Nombre de copies Maourou Diarra" %>
        <div class="input">
          <%= f.text_field :num_copies_emd,  {:class => "xlarge" } %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :series_title, "Titre de série" %>
        <div class="input">
          <%= f.text_field :series_title,  {:class => "xlarge" } %>
        </div>
      </div>
 
      <div class="clearfix">
        <%= f.label :series_number, "Numéro de série" %>
        <div class="input">
          <%= f.text_field :series_number,  {:class => "xlarge" } %>
        </div>
      </div>

       <div class="clearfix">
        <%= f.label :language, "Langue" %>
        <div class="input">
          <%= f.text_field :language,  {:class => "xlarge" } %>
        </div>
      </div>

      <div class="clearfix">
        <%= f.label :summary, "Résumé" %>
        <div class="input">
          <%= f.text_area :summary,  {:class => "xxlarge" } %>
        </div>
      </div>

    <div class="actions">
      <%= f.submit({ :class => "btn primary" }) %>
    </div>
  </fieldset>
  <% end %>

</div>

app/views/books/_full_book.html.erb
<h1><%= @book.title %></h1>
<% if current_user %>
<div class="checkout-bar">
<% if @book.checked_in > 0 %>
  <a class="btn" data-controls-modal="parent-checkout">Livre retiré</a>
<% end %>
<% if @book.checked_out > 0 %>
  <a class="btn" data-controls-modal="parent-checkin">Livre rendu</a>
<% end %>
<% end %>
</div>
  <table class="zebra-striped sorted">
      <tbody>
  <tr><td>Titre: </td><td><%= @book.title %></td></tr>
<tr><td>Auteur(s): </td><td><% @book.authors.each do |a| %><%= "#{a.last}, #{a.first}; "  %><% end %></td></tr>
  <tr><td>Date de publication: </td><td><%= @book.pub_year %></td></tr>
<tr><td>Sujet(s): </td><td><% @book.subjects.each do |a| %><%= "#{a.name}; "  %><% end %></td></tr>
  <tr><td>Genre: </td><td><%= @book.genre %></td></tr>
  <tr><td>Tranche d'âge: </td><td><%= @book.age_group %></td></tr>
  <tr><td>Nombre de pages: </td><td><%= @book.num_pages %></td></tr>
  <tr><td>Nombre totale de copies: </td><td>
      <span><%= @book.num_copies %> <span style="color: red; padding-right:10px;">-- <span id="copies-checked-out"><%= @book.checked_out %></span> copie(s) retiré(s) </span> </span>
      <% if @book.checked_out > 0 %>
        <a class="btn" data-controls-modal="parent-current-checkouts" data-backdrop="static">Voir liste</a>
      <% end %>
  </td></tr>
  <tr><td>Nombre de copies NEP:</td><td><%= @book.num_copies_nep %></td></tr>
  <tr><td>Nombre de copies Maouru Diarra:</td><td><%= @book.num_copies_emd %></td></tr>
  <tr><td>Titre de série: </td><td><%= @book.series_title %></td></tr>
  <tr><td>Numéro de série: </td><td><%= @book.series_number %></td></tr>
  <tr><td>Langue: </td><td><%= @book.language %></td></tr>
  <tr><td>Résumé: </td><td><%= @book.summary %></td></tr>
</tbody>
</table>
<% if current_user %>
  <div id="edit-bar" class="pull-right"><%= link_to("Statistiques", statistics_book_path(@book.id)) %> 
    | <%= link_to("Modifier", edit_book_path(@book.id)) %>
    | <span class="label important"><%= link_to 'Supprimer', @book, :confirm => "Est-ce que c'est vous êtes sûr que vous voulez supprimer cet livre?", :method => :delete,  :style => "color:white;" %></span>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1>Modifier l'inscription - ID #<%= @book.id %></h1>
<%= render 'form' %>

app/views/books/index.csv.erb
<%= @csv_string %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <div class="alert-message error" data-alert="true"><a href="#" class="close">x</a><%= flash[:notice] %></div>
<% end %>
<h1>Liste des livres:</h1>
<table class="zebra-striped sorted" >
  <thead><tr><th>Collection</th><th>Titre</th><th>Sujet</th></thead>
    <tbody>

      <%= render @books %>
    </tbody>
  </table>
  
    <div id="edit-bar" class="pull-right"><%= link_to "Télécharger comme CSV", books_path+ ".csv" %></div>

app/views/books/new.html.erb
<h1>Nouveau Livre</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<%= javascript_include_tag 'book-checkout' if current_user %>

<% if @from_search %>
  <ul class="breadcrumb">
    <li><%= link_to "← Chercher", :back %> <span class="divider">/</span></li>
    <li class="active"><%= @book.title %></li>
  </ul>
<% end %>

<div id="full-book-container">
  <%= render 'books/full_book' %>
</div>
<div id="parent-checkout" class="modal hide fade">
  <%= render 'checkout_items/checkout_form' %>
</div>
<div id="parent-checkin" class="modal hide fade">
  <%= render 'checkout_items/checkin_form' %>
</div>
<div id="parent-current-checkouts" class="modal hide fade">
  <%= render 'books/checkout_items' %>
</div>

app/views/books/statistics.html.erb
<%= javascript_include_tag 'stats' %>

<h2>Statistiques pour <u><%= @book.title %></u></h2>
<br />
  <table class="zebra-striped">
      <tbody>
        <tr><td>Retrait:</td><td><%= @book.checkout_items.count %> fois</td></tr>
        <% if @book.checkout_items.count == 0 %>
          <tr><td>Premier retrait:</td><td>N/A</td></tr>
          <tr><td>Retrait le plus recent:</td><td>N/A</td></tr>
        <% else %>
          <tr><td>Premier retrait:</td><td><%= @book.checkout_items[0].created_at.to_date %></td></tr>
          <tr><td>Retrait le plus recent:</td><td><%= @book.checkout_items[-1].created_at.to_date %></td></tr>
          <tr><td>Graph:</td><td><div id="graph-container" style="width:400px; height:300px;"></div></td></tr>
        <% end %>
      </tbody>
    </table>


    <h3>Qui a retiré(e) cet livre?</h3>
    <br />
    <table class="zebra-striped sorted" data-sort-column="0">
        <thead><th>Date</th><th>Notes</th></thead>
      <tbody>
          <% @book.checkout_items.each do |ci| %>
            <tr><td><%= ci.created_at.to_date %></td><td><%= ci.notes %></td></tr>
          <% end %>
          <% if @book.checkout_items.empty? %>
            <tr><td>Personne.</td></tr>
          <% end %>
        </tbody>
      </table>

    <div id="edit-bar" class="pull-right"><%= link_to "Télécharger comme CSV", statistics_book_path(@book) + ".csv" %></div>

app/views/books/temp_index.csv.erb
<%= @csv_string %>